name: GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Build Angular App
      run: ng build --output-path docs --base-href /my-resume/

    - name: Create .nojekyll File
      run: echo "" > docs/.nojekyll

    - name: Create 404.html Redirect
      run: cp docs/index.html docs/404.html

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./docs
